### PR TITLE
Optional queue connection configuration

### PR DESCRIPTION
**Pull request by Robertbaelde**
This PR adds optional queue configuration to the aggregate root repository. 

This is needed to limit parallel processing of queued consumers.

### CODE REVIEW

**Comment by driesvints** [comment]
Hey @Robertbaelde. Thanks for sending this in! It might still be a while before I get to these but appreciate the PRs 👍

**Comment by Robertbaelde** [comment]
@driesvints Do you have an estimation on when you'll be able to look at it? I don't want to pressure you at all, but like to know so we can decide if we have to fork this package or not 🍴

**Comment by driesvints** [comment]
Hey @Robertbaelde, sorry this is taking longer. In general I don't plan to extensively work on the package any time soon but I think I can get this PR in over the weekend. I'll let you know by Monday.

**Comment by driesvints** [comment]
I've renamed `setQueue` to `onQueue` so it's the same as the Laravel internals. Thanks for this PR @Robertbaelde! I'll get this tagged in a bit.

**Comment by driesvints** [comment]
Released 0.3.1 with this.

**Pull request merged**
